name: Test

on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: make deploy-stack ENV=prod
